import Head from "next/head";
import styles from "../styles/Home.module.css";
import { client } from "./_app";

import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import { Fragment } from "react";

import LaunchesList from '../components/launches/LaunchesList';

export default function Home() {
  
  return (
    <Fragment>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LaunchesList ></LaunchesList>
    </div>
    </Fragment>
  );
}

