import Head from "next/head";
import styles from "../styles/Home.module.css";
import { client } from "./_app";

import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import { Fragment } from "react";

import LaunchesList from './LaunchesList';

export default function Home() {
  //console.log('launches', launches);
  return (
    <Fragment>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LaunchesList ></LaunchesList>
    </div>
    </Fragment>
  );
}

// export async function getStaticProps() {

//   const { data } = await client.query({
//     query: gql`
//       query GetLaunches {
//         launchesPast(limit:10) {
//           id
//           mission_name
//           launch_date_local
//           launch_site {
//             site_name_long
//           }
//           details
//           links {
//             article_link
//             video_link
//             mission_patch
//             wikipedia
//           }
//           rocket {
//             rocket_name
//           }
//         }
//       }
//     `,
//   });

//   return {
//     props: {
//       launches: data.launchesPast,
//     },
//   };
// }
